[package]
name = "bot-lib"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { workspace = true }
color-eyre = { workspace = true }
poise = { workspace = true }
tracing = { workspace = true }
bot-llm = { workspace = true }
rand = { workspace = true }
dashmap = { workspace = true }
chrono = "0.4.38"
serde = { version = "1.0.198", features = ["derive", "rc"] }
toml = "0.8.12"
regex = "1.10.4"
nom = "7.1.3"
emojis = "0.6.1"
notify = { version = "6.1.1", default-features = false, features = [
    "macos_kqueue",
] }
itertools = "0.11.0"
serde_with = { version = "3.7.0", features = ["chrono"] }
futures = "0.3.30"
tap = "1.0.1"
colored = "2.1.0"
tracing-log = "0.2.0"
parking_lot = "0.12.1"
fundu = { version = "2.0.0", features = ["chrono"] }
reqwest = { version = "0.12.3", features = ["json", "blocking"] }
serde_json = "1.0.116"
tokio-stream = "0.1.15"
crossbeam-channel = "0.5.13"
raur = "7.0.0"
sled = "0.34.7"
bincode = "1.3.3"
